/*
 * ContactPanel.java
 *
 * Created on 27. März 2007, 18:43
 */

package org.jdesktop.xswingx.demo;

import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;

import javax.swing.border.EmptyBorder;
import javax.swing.border.LineBorder;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.DateFormatter;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.JTextComponent;

/**
 * 
 * @author peterw
 */
public class ContactPanel extends javax.swing.JPanel {
    /** Creates new form ContactPanel */
    public ContactPanel() {
        initComponents();
        setOpaque(true);
        DateFormatter dateFormatter = new DateFormatter(new SimpleDateFormat(jLabelFormattedTextField1.getPrompt())){
            public Object stringToValue(String text) throws ParseException {
                if(text == null || text.length() == 0){
                    return null;
                }
                return super.stringToValue(text);
            }
        };
        jLabelFormattedTextField1.setFormatterFactory(new DefaultFormatterFactory(dateFormatter));
        for (Component c : getComponents()) {
            if (c instanceof JTextComponent) {
                final JTextComponent txt = (JTextComponent) c;

                txt.setOpaque(false);
                txt.setBorder(new EmptyBorder(1,1,1,1));
                txt.addFocusListener(new FocusAdapter() {
                    public void focusGained(FocusEvent e) {
                        txt.setBorder(new LineBorder(Color.GRAY));
                        txt.selectAll();
                    }

                    public void focusLost(FocusEvent e) {
                        txt.setBorder(new EmptyBorder(1,1,1,1));
                        
                        txt.invalidate();
                        txt.getParent().validate();
                    }
                });
                txt.getDocument().addDocumentListener(new DocumentListener(){
                    public void changedUpdate(DocumentEvent e) {
                        change();
                    }

                    public void insertUpdate(DocumentEvent e) {
                        change();
                    }

                    public void removeUpdate(DocumentEvent e) {
                        change();
                    }
                    
                    private void change() {
                        txt.invalidate();
                        txt.getParent().validate();
                    }
                });
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabelTextField1 = new org.jdesktop.xswingx.JXPromptField();
        jLabelTextField2 = new org.jdesktop.xswingx.JXPromptField();
        jLabelTextField3 = new org.jdesktop.xswingx.JXPromptField();
        jLabelFormattedTextField1 = new org.jdesktop.xswingx.JXFormattedPromptField();
        jLabel1 = new javax.swing.JLabel();
        jLabelTextField4 = new org.jdesktop.xswingx.JXPromptField();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabelTextArea1 = new org.jdesktop.xswingx.JXPromptArea();

        setBackground(new java.awt.Color(255, 255, 255));
        jLabelTextField1.setBorder(null);
        jLabelTextField1.setToolTipText("You must enter a First Name");
        jLabelTextField1.setFont(jLabelTextField1.getFont().deriveFont(Font.BOLD, 14f));
        jLabelTextField1.setPrompt("First Name");
        jLabelTextField1.setPromptColor(java.awt.Color.red);

        jLabelTextField2.setBorder(null);
        jLabelTextField2.setFont(jLabelTextField2.getFont().deriveFont(Font.BOLD, 14f));
        jLabelTextField2.setPrompt("Last Name");

        jLabelTextField3.setBorder(null);
        jLabelTextField3.setPrompt("Company");

        jLabelFormattedTextField1.setBorder(null);
        jLabelFormattedTextField1.setPrompt("MM/dd/yy");

        jLabel1.setText("born");

        jLabelTextField4.setBorder(null);
        jLabelTextField4.setFont(jLabelTextField4.getFont().deriveFont(Font.BOLD, 14f));
        jLabelTextField4.setPrompt("Prefix");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 380, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 50, Short.MAX_VALUE)
        );

        jLabelTextArea1.setPrompt("Notes");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabelTextArea1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(jLabelTextField4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabelTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabelTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 108, Short.MAX_VALUE)
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabelFormattedTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jLabelTextField3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jSeparator1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabelTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabelFormattedTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1)
                    .add(jLabelTextField4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabelTextField3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabelTextArea1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private org.jdesktop.xswingx.JXFormattedPromptField jLabelFormattedTextField1;
    private org.jdesktop.xswingx.JXPromptArea jLabelTextArea1;
    private org.jdesktop.xswingx.JXPromptField jLabelTextField1;
    private org.jdesktop.xswingx.JXPromptField jLabelTextField2;
    private org.jdesktop.xswingx.JXPromptField jLabelTextField3;
    private org.jdesktop.xswingx.JXPromptField jLabelTextField4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

}
