/*
 * TestPanel.java
 *
 * Created on 28. März 2007, 12:40
 */

package org.jdesktop.xswingx.demo;

import java.awt.Color;
import java.awt.FlowLayout;

import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

import org.jdesktop.xswingx.PromptSupport;

/**
 *
 * @author  peterw
 */
public class TestPanel extends javax.swing.JPanel {
    
    /** Creates new form TestPanel */
    public TestPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabelTextField1 = new org.jdesktop.xswingx.JXPromptField();
        jLabelTextField2 = new org.jdesktop.xswingx.JXPromptField();
        jLabelTextField3 = new org.jdesktop.xswingx.JXPromptField();
        jLabelTextField4 = new org.jdesktop.xswingx.JXPromptField();
        jLabelTextField5 = new org.jdesktop.xswingx.JXPromptField();
        jLabelTextField6 = new org.jdesktop.xswingx.JXPromptField();
        jLabelTextField7 = new org.jdesktop.xswingx.JXPromptField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabelTextArea1 = new org.jdesktop.xswingx.JXPromptArea();

        jLabelTextField1.setPrompt("Prompt Text");

        jLabelTextField2.setColumns(20);
        jLabelTextField2.setPrompt("20 Columns");

        jLabelTextField3.setPrompt("Red");
        jLabelTextField3.setPromptColor(java.awt.Color.red);

        jLabelTextField4.setPrompt("Not Opaque");
        jLabelTextField4.setOpaque(false);

        jLabelTextField5.setColumns(10);
        jLabelTextField5.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jLabelTextField5.setPrompt("Trailing");

        jLabelTextField6.setBackground(java.awt.Color.yellow);
        jLabelTextField6.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        jLabelTextField6.setForeground(java.awt.Color.red);
        jLabelTextField6.setCaretColor(java.awt.Color.red);
        jLabelTextField6.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabelTextField6.setPrompt("Different");
        jLabelTextField6.setPromptColor(java.awt.Color.magenta);
        jLabelTextField6.setSelectedTextColor(java.awt.Color.orange);
        jLabelTextField6.setSelectionColor(java.awt.Color.black);

        jLabelTextField7.setColumns(10);
        jLabelTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jLabelTextField7.setPrompt("Center");

        jLabelTextArea1.setColumns(20);
        jLabelTextArea1.setRows(5);
        jLabelTextArea1.setPrompt("Prompt Text");
        jScrollPane1.setViewportView(jLabelTextArea1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabelTextField6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(jLabelTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabelTextField3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabelTextField4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(jLabelTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabelTextField5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabelTextField7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabelTextField3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabelTextField4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelTextField5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabelTextField7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabelTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabelTextField6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.xswingx.JXPromptArea jLabelTextArea1;
    private org.jdesktop.xswingx.JXPromptField jLabelTextField1;
    private org.jdesktop.xswingx.JXPromptField jLabelTextField2;
    private org.jdesktop.xswingx.JXPromptField jLabelTextField3;
    private org.jdesktop.xswingx.JXPromptField jLabelTextField4;
    private org.jdesktop.xswingx.JXPromptField jLabelTextField5;
    private org.jdesktop.xswingx.JXPromptField jLabelTextField6;
    private org.jdesktop.xswingx.JXPromptField jLabelTextField7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
    public static void main(String[] args) {
		JFrame f = new JFrame();
		f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		f.setLayout(new FlowLayout());
		f.add(new JTextField());
		JTextField tf = new JTextField();
		f.add(tf);
		PromptSupport.install("Enter Text", tf);
		
		JTextArea ta = new JTextArea();
		ta.setColumns(10);
		ta.setRows(5);
		f.add(new JScrollPane(ta));
		PromptSupport.install("Enter Text", ta);
		
		f.pack();
		f.setVisible(true);
	}
}
